# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry;
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - prod
    - develop
    - staging

resources:
  - repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b8753fd3-05c7-4436-b521-6b80fd43df38'
  imageRepository: $(Build.SourceBranchName)--$(Build.DefinitionName)
  containerRegistry: 'httechtest.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  gitCommit: $(Build.SourceVersion)
  gitBranch: $(Build.SourceBranchName)
  isDevelop: $[eq(variables['Build.SourceBranchName'], 'develop')]
  isStaging: $[eq(variables['Build.SourceBranchName'], 'staging')]
  isProduction: $[eq(variables['Build.SourceBranchName'], 'prod')]

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Test
    displayName: Test Stage
    jobs:
      - job: Test
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Maven@3
            displayName: Test MVN version
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - script: echo $(gitCommit)-$(gitBranch)
      - task: Docker@2
        displayName: Build & Push to ACR
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(gitCommit)
